module.exports = [
  {
    id: 1,
    name: "Calça Jeans Mylus",
    description: "",
    price: "R$40,00",
    oldPrice: "",
    discount: false,
    stock: 2,
  },
  {
    id: 2,
    name: "Camiseta Pollo Azul",
    description: "",
    price: "R$20,00",
    oldPrice: "R$50,00",
    discount: true,
    stock: 4,
  },
  {
    id: 3,
    name: "Saia Jeans",
    description: "",
    price: "R$25,00",
    oldPrice: "R$35,00",
    discount: true,
    stock: 3,
  },
  {
    id: 4,
    name: "Vestido Xadrex",
    description: "",
    price: "R$45,00",
    oldPrice: "",
    discount: false,
    stock: 8,
  },
  {
    id: 5,
    name: "Casaco Jeans Mylus",
    description: "",
    price: "R$55,00",
    oldPrice: "R$65,00",
    discount: true,
    stock: 9,
  },
];
